name: reflection_factory
description: Allows Dart reflection with an easy approach, even for third-party classes, using code generation portable for all Dart platforms.
version: 1.2.0
homepage: https://github.com/gmpassos/reflection_factory

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  build: ^2.2.1
  analyzer: ^4.1.0
  dart_style: ^2.2.3
  meta: ^1.8.0
  mime: ^1.0.2
  base_codecs: ^1.0.1
  pub_semver: ^2.0.0
  path: ^1.8.2
  collection: ^1.16.0
  yaml: ^3.1.0
  source_span: ^1.8.2

dev_dependencies:
  build_runner: ^2.1.11
  build_test: ^2.1.3
  lints: ^2.0.0
  pubspec: ^2.2.0
  data_serializer: ^1.0.3
  dependency_validator: ^3.1.0
  test: ^1.21.2
  coverage: ^1.3.2
